name: "Icon actions"

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "icons/**"

jobs:
  desktop:
    runs-on: "ubuntu-latest"
    name: "Format desktop icons"
    if: ${{ contains(github.event.commits.*.modified, 'icons/desktop') }}
    permissions:
      contents: "write"
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install dependencies
        working-directory: ./.github/actions
        run: npm ci
      - name: Update desktop icons
        uses: ./.github/actions/dist/desktop-transform
        with:
          files: "icons/desktop/**/*.svg"
      - name: Commit changes
        uses: ./.github/actions/dist/commit-changes
        with:
          message: "Updated desktop icons to match format conventions"
  mobile:
    runs-on: "ubuntu-latest"
    name: "Format mobile icons"
    if: ${{ !cancelled() && contains(github.event.commits.*.modified, 'icons/mobile') }}
    needs: desktop
    permissions:
      contents: "write"
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install dependencies
        working-directory: ./.github/actions
        run: npm ci
      - name: Update mobile svg icons
        uses: ./.github/actions/dist/mobile-transform
        with:
          files: "icons/mobile/**/*.svg"
          file_type: "svg"
      - name: Update mobile xml icons
        uses: ./.github/actions/dist/mobile-transform
        with:
          files: "icons/mobile/**/*.xml"
          file_type: "xml"
      - name: Commit changes
        uses: ./.github/actions/dist/commit-changes
        with:
          message: "Updated mobile icons to match format conventions"