name: "Mobile icons"

on:
  push:
    branches:
      - "main"
    paths:
      - "icons/mobile/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "icons/mobile/**"

jobs:
  format:
    runs-on: "ubuntu-latest"
    name: "Format mobile icons"
    permissions:
      contents: "write"
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install dependencies
        working-directory: ./.github/actions
        run: npm ci
      - name: Update mobile svg icons
        uses: ./.github/actions/dist/mobile-transform
        with:
          files: "icons/mobile/**/*.svg"
          file_type: "svg"
      - name: Update mobile xml icons
        uses: ./.github/actions/dist/mobile-transform
        with:
          files: "icons/mobile/**/*.xml"
          file_type: "xml"
      - name: Commit changes
        uses: ./.github/actions/dist/commit-changes
        with:
          message: "Updated mobile icons to match format conventions"
